### ISSUE TITLE
Manually curated signatures

### ISSUE THREAD

**Issue by france-hub** [federicomarini/quantiseqr#23]
Ciao!

Thanks for this package. 
I was wondering whether quantiseqr allows manually curated signatures for the immune deconvolution.

Thank you
Francesco

**Comment by federicomarini** [comment]
Hi Francesco,

In theory it does - the parameter is in for that reason.
@FFinotello is the main designer of the signatures and their structure, I am tagging her in here to notify her.
I cannot really help you too much on this, as I stepped into the project at a later point to make it Bioc-ready 😉 
Federico

**Comment by FFinotello** [comment]
Ciao Francesco,

Unfortunately, quanTIseq does not support user-provided signatures, due to its approaches to account for cell-type-specific mRNA abundance and CD4-Treg multicollinearity, both of which are based on the TIL10 signature matrix.

I hope this helps despite the negative outcome,
Francesca

**Comment by france-hub** [comment]
Ok, thank you both for your answers!

Best,
Francesco

**Comment by federicomarini** [comment]
I hope I did not mislead you into thinking otherwise.
But as Francesca nicely put, quantiseqr (and quanTIseq) work like a charm with the TIL10 signature matrix.
There would be some advanced steps to take care of to enable other signatures to work "out of the box", and I guess the plan was to not put this burden on the users.

**Comment by france-hub** [comment]
Oh, no. I got your point and understand.

Thank you!
